### ISSUE TITLE
Status 610 in Developer Console log

### ISSUE THREAD

**Issue by ghost** [sipgate-io/sipgateio-incomingcall-python#1]
Thanks for this example, I installed it on my server to test it. Everything works fine, but in the developer console in the debug log it shows status 610 instead of status 240. The script outputs "127.0.0.1 - - [17/Oct/2021 11:55] "POST / HTTP/1.1" 204
It would be nice to know where there is an error. Does the response never receive the sender or is there something wrong in the debug log view?
Thanks,
Manuel

**Comment by nilsreck** [comment]
Hello,

we are happy to hear that the example works fine for you. However, we are not able to replicate your issue regarding the 610 HTTP Error.

Best regards,
Nils from sipgate.io
